#!/usr/bin/env zsh

export DOTFILES="$HOME/dotfiles"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export HISTFILE="$ZDOTDIR/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=100000

export XINITRC="$XDG_CONFIG_HOME/X11/.xinitrc"

export I3CONFIG="$XDG_CONFIG_HOME/i3"

export VIMCONFIG="$XDG_CONFIG_HOME/nvim"

export EDITOR="nvim"
export VISUAL="nvim"

export TERMINAL="/usr/bin/alacritty"

export OPENER="xdg-open"

export BROWSER="firefox"

export VIDEO_PLAYER="mpv"

# Set clang for export in cmake
export CC="clang"
export CXX="clang++"

