#!/usr/bin/env zsh

unsetopt beep

# Push the current directory visited on to the stack
setopt AUTO_PUSHD
# Do not store duplicate directories in the stack
setopt PUSHD_IGNORE_DUPS
# Do not print the directory stack after using pushd or popd
setopt PUSHD_SILENT

fpath=($ZDOTDIR/external $fpath)

source "$DOTFILES/zsh/external/completion.zsh"
autoload -Uz compinit; compinit
# Autocomplete hidden files
_comp_options+=(globdots)

autoload -Uz prompt_purification_setup && prompt_purification_setup
autoload -Uz cursor_mode && cursor_mode
autoload -Uz edit-command-line
zle -N edit-command-line

source "$XDG_CONFIG_HOME/zsh/.aliases"
source "$DOTFILES/zsh/scripts.zsh"
source "$DOTFILES/zsh/external/bd.zsh"

if [ $(command -v "fzf") ]; then
    source /usr/share/fzf/completion.zsh
    source /usr/share/fzf/key-bindings.zsh
fi
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_COMMAND="$FZF_DEFAULT_COMMAND"

# Include lfcd function that changes current working dir in shell after exiting lf 
LFCD="/home/dima/.config/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi
# Bind <c-o> to start lf using lfcd function
bindkey -s '^o' 'lfcd\n'

# Enable vim mode
bindkey -v
bindkey -M viins 'jk' vi-cmd-mode

# Use vim keybindings to navigate in completion menu 
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Edit comand in nvim
bindkey -M vicmd v edit-command-line

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Unbind Ctrl-l - default clean shell keybinding in favor of tmux pane navigation
bindkey -r '^l'
bindkey -r '^g'
bindkey '^g' .clear-screen
